"""add_society_security_and_servicer_mastery

Revision ID: 22d8461d1634
Revises: 
Create Date: 2026-03-17 15:59:50.241027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d8461d1634'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_bookings', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('service_bookings', sa.Column('issue_description', sa.Text(), nullable=True))
    op.add_column('service_bookings', sa.Column('photos', sa.Text(), nullable=True))
    op.add_column('service_bookings', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.add_column('service_bookings', sa.Column('final_cost', sa.Float(), nullable=True))
    op.add_column('service_bookings', sa.Column('property_details', sa.Text(), nullable=True))
    op.add_column('service_bookings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('service_bookings', 'notes')
    op.add_column('service_providers', sa.Column('hourly_rate', sa.Float(), nullable=True))
    op.add_column('service_providers', sa.Column('availability', sa.Text(), nullable=True))
    op.add_column('societies', sa.Column('secretary_name', sa.String(), nullable=True))
    op.add_column('societies', sa.Column('is_legal', sa.Boolean(), nullable=True))
    op.add_column('societies', sa.Column('registration_number', sa.String(), nullable=True))
    op.add_column('societies', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('societies', sa.Column('secretary_id', sa.Integer(), nullable=True))
    op.add_column('societies', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'societies', ['registration_number'])
    op.create_foreign_key(None, 'societies', 'users', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'societies', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'societies', 'users', ['secretary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'societies', type_='foreignkey')
    op.drop_constraint(None, 'societies', type_='foreignkey')
    op.drop_constraint(None, 'societies', type_='foreignkey')
    op.drop_constraint(None, 'societies', type_='unique')
    op.drop_column('societies', 'manager_id')
    op.drop_column('societies', 'secretary_id')
    op.drop_column('societies', 'owner_id')
    op.drop_column('societies', 'registration_number')
    op.drop_column('societies', 'is_legal')
    op.drop_column('societies', 'secretary_name')
    op.drop_column('service_providers', 'availability')
    op.drop_column('service_providers', 'hourly_rate')
    op.add_column('service_bookings', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('service_bookings', 'updated_at')
    op.drop_column('service_bookings', 'property_details')
    op.drop_column('service_bookings', 'final_cost')
    op.drop_column('service_bookings', 'estimated_cost')
    op.drop_column('service_bookings', 'photos')
    op.drop_column('service_bookings', 'issue_description')
    op.drop_column('service_bookings', 'priority')
    # ### end Alembic commands ###
