"""add routine task fields to maintenance_tasks

Revision ID: 90393c05f34f
Revises: f1a2b3c4d5e6
Create Date: 2026-03-24 18:55:13.187297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90393c05f34f'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_tasks', sa.Column('category', sa.String(), nullable=True))
    op.add_column('maintenance_tasks', sa.Column('location', sa.String(), nullable=True))
    op.add_column('maintenance_tasks', sa.Column('task_type', sa.String(), nullable=True))
    op.add_column('maintenance_tasks', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.add_column('maintenance_tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'maintenance_tasks', 'service_bookings', ['booking_id'], ['id'])
    op.alter_column('maintenance_tasks', 'due_date', existing_type=sa.Date(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance_tasks', 'due_date', existing_type=sa.Date(), nullable=False)
    op.drop_constraint(None, 'maintenance_tasks', type_='foreignkey')
    op.drop_column('maintenance_tasks', 'created_at')
    op.drop_column('maintenance_tasks', 'booking_id')
    op.drop_column('maintenance_tasks', 'task_type')
    op.drop_column('maintenance_tasks', 'location')
    op.drop_column('maintenance_tasks', 'category')
    # ### end Alembic commands ###
