"""expand_provider_profile_and_certificates

Revision ID: e018acc20df6
Revises: eca720589979
Create Date: 2026-03-17 17:15:31.404512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e018acc20df6'
down_revision: Union[str, None] = 'eca720589979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('certificate_url', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_certificates_id'), 'service_certificates', ['id'], unique=False)
    op.add_column('service_providers', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('service_providers', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('service_providers', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('service_providers', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('service_providers', sa.Column('categories', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_providers', 'categories')
    op.drop_column('service_providers', 'gender')
    op.drop_column('service_providers', 'age')
    op.drop_column('service_providers', 'last_name')
    op.drop_column('service_providers', 'first_name')
    op.drop_index(op.f('ix_service_certificates_id'), table_name='service_certificates')
    op.drop_table('service_certificates')
    # ### end Alembic commands ###
