"""fix_society_relationships_and_add_servicer_fields

Revision ID: eca720589979
Revises: 22d8461d1634
Create Date: 2026-03-17 16:22:39.542512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca720589979'
down_revision: Union[str, None] = '22d8461d1634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_providers', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('service_providers', sa.Column('education', sa.String(), nullable=True))
    op.add_column('service_providers', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('service_providers', sa.Column('availability_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_providers', 'availability_status')
    op.drop_column('service_providers', 'experience_years')
    op.drop_column('service_providers', 'education')
    op.drop_column('service_providers', 'bio')
    # ### end Alembic commands ###
